### ISSUE TITLE
Did you remove prettyConjugation?

### ISSUE THREAD

**Issue by gegnew** [b3nj5m1n/moderncardthemes#3]
It doesn't appear to be in the deck any longer

**Comment by b3nj5m1n** [comment]
I've just checked and the card appears to be there, could you download the current version and re-import it, then see if it's there?

**Comment by gegnew** [comment]
Sorry, I missed your reply. When I import the deck I only see:

![image](https://user-images.githubusercontent.com/35822787/109763492-7464d780-7bf2-11eb-9ef7-b4648b00e9f3.png)


I also get the following error when I try to import:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.9.1 Qt 5.15.2 PyQt 5.15.2
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2021-03-03 07:39:16
Add-ons possibly involved: ⁨CrowdAnki JSON exportimport Edit history Collaborate on deck creation⁩

Caught exception:
Traceback (most recent call last):
  File "/home/g/.local/share/Anki2/addons21/1788670778/anki/ui/action_vendor.py", line 31, in <lambda>
    lambda: AnkiJsonImporter.import_deck(self.window.col, self.directory_vendor))
  File "/home/g/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 112, in import_deck
    AnkiJsonImporter.import_deck_from_path(collection, Path(directory_path))
  File "/home/g/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 101, in import_deck_from_path
    if importer.load_deck(directory_path):
  File "/home/g/.local/share/Anki2/addons21/1788670778/importer/anki_importer.py", line 39, in load_deck
    deck.save_to_collection(self.collection, import_config=import_config)
  File "/home/g/.local/share/Anki2/addons21/1788670778/representation/deck.py", line 131, in save_to_collection
    self.save_decks_and_notes(collection=collection,
  File "/home/g/.local/share/Anki2/addons21/1788670778/representation/deck.py", line 154, in save_decks_and_notes
    note.save_to_collection(collection, self, model_map_cache, import_config=import_config)
  File "/home/g/.local/share/Anki2/addons21/1788670778/representation/note.py", line 115, in save_to_collection
    self.handle_import_config_changes(import_config, note_model)
  File "/home/g/.local/share/Anki2/addons21/1788670778/representation/note.py", line 131, in handle_import_config_changes
    if import_config.is_personal_field(note_model.anki_dict['name'], note_model.anki_dict['flds'][num]['name']):
IndexError: list index out of range

```

**Comment by gegnew** [comment]
Wow, sorry that image is so huge

**Comment by b3nj5m1n** [comment]
I just tried with a fresh profile and I have the same problem. I'll try to look into it a bit more, but I believe the issue might be with CrowdAnki.

**Comment by b3nj5m1n** [comment]
@gegnew I raised an issue with CrowdAnki, see [#121](https://github.com/Stvad/CrowdAnki/issues/121).

After applying the temporary fix, the export in this repo is now complete and doesn't throw any errors when importing.

I have also verified with a test profile that every note type does indeed get imported correctly.

If you could, please check yourself and close this issue if it works for you.

**Comment by gegnew** [comment]
This seems to have solved the problem, thanks!
